### ISSUE TITLE
Lethal temperatures are not Lethal.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1122]
#### Brief description of the issue
People with prosthetics run normal temperatures of 105-110 Fahrenheit. (That would kill someone.)
#### What you expected to happen
People running fevers of 105+ to actually suffer negative effects.
#### What actually happened
Fevers can run as high as they like without causing damage.
#### Steps to reproduce
Obtain prosthetics. 
Cut self. Obtain infection.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-03-04
d66ffcdbbfa6ddf9da3517570615b81ffe2ae8ee

**Comment by Serithi** [comment]
But if you think about it, if the lethal temperatures aren't lethal, then they aren't lethal temperatures and by definition there's no problem :^)

**Comment by Spookerton** [comment]
This is probably because human exterior temperature tolerance is not different from body temperature tolerance. Adjusting the danger threshholds would be problematic because you could start killing people by turning the thermostat up.

That said, heat is totally not damaging enough once it's past threshold. Anecdotally, I've seem people stroll into 700C rooms without internals or suits, have gun-fights, and then limp out minutes later with more brute from rubbers than burns.

**Comment by OhEmGee** [comment]
Please don't fix this, it would be seriously impeding to people with prosthetics.

Wasn't the whole heat thing added in the first place so FBP's couldn't spacewalk infinitely?

I mean, think about it. A human with prosthetics would have to carry a cooler and a oxygen tank to prevent cooking in their voidsuit, while a FBP needs to only carry a cooler. Ergo, the human with prosthetics is significantly disadvantaged.

**Comment by zekesulastin** [comment]
A little bit of a necropost, but keep in mind that the temperature thresholds in general aren't really based on realism.  You can reach 105F from a stage one (of four) sickness, etc.

**Comment by Anewbe** [comment]
No longer applicable, closing
