### ISSUE TITLE
AI / Cyborgs / pAI don't understand the Teshari language.

### ISSUE THREAD

**Issue by bobbob212** [PolarisSS13/Polaris#1448]
**Brief description of the issue**
As AI / Cyborg you are unable to understand the Teshari language, but can understand all others basically.
As pAI with the universal translator active you are unable to speak/understand the Teshari language

**What you expected to happen**
Understanding the language as AI / pAI with universal translator.

**What actually happened**
Not understanding language as AI / pAI with universal translator.

**Steps to reproduce**
 Be AI / Cyborg
 Be pAI and download and activate universal translator.

Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

**Comment by Neerti** [comment]
Zuhayr said this is intentional due to the race in-character being 'new to the galactic stage', so to say, if I remember correctly. I'm not sure how long he intended for that to be, however.

**Comment by Nerezza** [comment]
It's not being kept track of anywhere I think, but it's been like 3 months since they've started showing up on the northern star fluff-wise.

The lack of Schechi understanding for synthetics doesn't have much impact on communication since Teshari are generally fully Skrellian fluent too, so they can warble to the synthetics if they have trouble saying something in common. ;>

**Comment by bobbob212** [comment]
But how am I supposed to ease drop on all of the crew?!

**Comment by Mechoid** [comment]
When I asked Zuhayr the week they were added, he said it was only going to be a week or two that synths couldn't understand them. It has been much longer than those two weeks, now.
