### ISSUE TITLE
Cash Register

### ISSUE THREAD

**Issue by AliciaJewel** [PolarisSS13/Polaris#1452]
#### Brief description of the issue
The cash register (at least the one in the kitchen) will not process custom orders or delete entries.

#### What you expected to happen
The cash register to process custom orders and delete entries.

#### What actually happened
It doesn't.

#### Steps to reproduce
1) Attempt to add a customer order to the cash register in the kitchen and see that it doesn't work.
2) Scan a valid item with the cash register.
3) Attempt to remove the previous item from the register and fail.

#### Additional info:
 - **Server Revision**: 28ab131610b5e7e98a2b847af76292b4a30880c7
 - **Anything else you may wish to add** N/A

**Comment by RoseCG** [comment]
Can confirm this issue. During a round I tried to register a meat steak, but it wasn't on the database. Attempted to make a custom order, clicked on "Custom Order", nothing happened.

Same thing if I want to delete an order.

**Comment by Arokha** [comment]
This is a very strange issue. It only happens on registers that are on the map at world start. If you spawn them later, they do not have this bug. If I delete and spawn another register in the bar, it works as expected.

**Comment by SpadesNeil** [comment]
Assuming Polaris still uses Initialize(), I suspect something in the Initialize() proc is behaving badly.

**Comment by Arokha** [comment]
Actually it has some vars overridden on the map. I believe it's due to the 'tag' var.

**Comment by Arokha** [comment]
Ok. This is caused by the 'tag' var. 'Tag' is a way to make objects named so you can refer to them by name from anywhere else rather than needing to get a reference to them. When Topic runs when you click something, more than one register with the same Tag get evaluated for if you have proximity to the register to keep using it.

This is why the UI 'dies', because it thinks you are too far away (it may be checking the register in the coffee shop while you're in the bar or whatever) because they all have the same reference now.

The way 'tag' got there is that it was set automatically when 'Generate Instances from Directions' was used in the map editor as a simple way to get the four directions of cash registers and place them easier. However, 'Generate Instances from Directions' automatically tags the four directions, and would break anything that uses Topic (aka anything with a UI). APCs, Air Alarms, other things with a UI that have more than one direction all have four item definitions, one for each direction.

So, lesson is: Don't use 'Generate Instances from Directions' on anything with a UI that uses Topic (which is basically everything).
