### ISSUE TITLE
Communicators transmit video feed to officers.

### ISSUE THREAD

**Issue by OrbisAnima** [PolarisSS13/Polaris#1975]
#### Brief description of the issue
Any communicator with visibility on will allow officers or Ai's to view all around the person carrying the communicator.

#### What you expected to happen
To have a portable device that allows me to communicate with others, instead of a portable camera that allows for all crazy kinds of privacy breachs during code green, or just make players not to pick the communicator.

At the very least this should be a different item, ie, portable camera.

#### What actually happened
Officers began to spawn more often and actually stare at the cameras. A traitor round was ruined.

#### Steps to reproduce
-Get a communicator from the loadout
-Go to the camera list of security
-Find your own name there if you toggled the identity on your prefferences, otherwise search for the communicators list and you will be able to look at it.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Revision Unknown.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
You have an option on the communicator to turn the visibility for cameras on, or off, I believe. It's a feature.

**Comment by OrbisAnima** [comment]
It comes on by default?

**Comment by OrbisAnima** [comment]
From my tests, if you wanted to be able to be called by ghosts, to be seen as a callable person, then you had to toggle visibility on. That's not a different button to not be on the security feds videos, either you have a working phone with security seeing your every movement, or you have a weight two object that does nothing unless someone inside the game, not a ghost, has your ip number.

**Comment by OrbisAnima** [comment]
Look, the fix we we will implement on our server is simple, we add  on line 56 of  code/__defines/machinery.dm, NETWORK_COMMUNICATORS as a restricted type, becouse we believe having security watch you through your phone, as default, is kinda bad.

**Comment by Arokha** [comment]
It was intentional but just add another button that removes the camera network. Just look at the visibility toggle proc and use that same add/remove network call in a new camera visibility toggle.

That way you offer the most options for people who want to use the cameras for scouting for security or whatnot. Not a fan of removing options from players, more a fan of giving options.

**Comment by OrbisAnima** [comment]
Hrm, yes, that makes more sense, and I believe I could upstream that one, so we all get something out of it.

**Comment by mwerezak** [comment]
I'm pretty sure you can have a reduced view size for the camera, why but restrict it to only show stuff at close distance?

**Comment by Arokha** [comment]
It does. You can only see for a few turfs. 4 in each direction I think.

**Comment by mwerezak** [comment]
Maybe drop it to 2?

**Comment by Neerti** [comment]
It uses the welder overlay atm IIRC.

Reducing it to two tiles would be a bit ugly to look at as a ghost.

Anyways, my opinion is that the cameras in communicators shouldn't show up on the security consoles, since it's quite a power spike.  It'd be pretty cool if an enterprising antag somehow managed to remotely hack into the camera with EPv2 or something, but yeahhhhh.

**Comment by OrbisAnima** [comment]
Well, I was testing a bit, an "emaged" security monitor that added the communicators cameras would be pretty good, yet it would make the emag yet more indispensable, still, the temptation is there.

**Comment by Magneld** [comment]
Any way to make this start off deactivated but on alert level change available?
