### ISSUE TITLE
Hardsuit break support.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#2032]
#### Brief description of the issue
A hardsuit will support a broken limb until removed, but putting the suit back on will not re-splint the break.
#### What you expected to happen
The hardsuit to support the break when put back on after being bandaged.
#### What actually happened
The break stopped being splinted.
#### Steps to reproduce
Break an arm in a hardsuit, remove and replace the hardsuit and be unable to use the arm.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SinTwo** [comment]
I believe this is actually intentional. Your limb is broken, but held in place by the suit, then when you disengage the suit the limb just falls out of place and so when you engage the suit again, it's not magically putting the bone back in place like a splint, it's just closing atop the now misaligned bone.

**Comment by Yoshax** [comment]
This is intended. What Sin said is correct.
