### ISSUE TITLE
Zones merge across doorways

### ISSUE THREAD

**Issue by Hubblenaut** [PolarisSS13/Polaris#2277]
#### Brief description of the issue

For some funny reason, zones merge across doorways. This is actually an amazing feat, given that it makes gas transfer between zones more efficient even though ZAS has to iterate through every turf on the z-level each time a door is opened or closed.
Since this is not **supposed** to happen however, I'll mark it as an issue so people are aware ZAS is not functioning as expected right now (even while funnily enough, this is highly appreciable). It could be connected to other bugs with ZAS right now that have not been noticed yet.
#### What you expected to happen

Zones usually should not merge across doorways due to having to be rebuilt every single time. There is a variable on doors, `block_air_zones`, which should prevent exactly that on call of `CanPass(atom/movable/mover, turf/target, height=0, air_group=0)`.
#### What actually happened

![Image](http://i.imgur.com/sSX6BJ6.png)
#### Steps to reproduce

Open a door and use the ZAS debug verbs to highlight zones.
#### Additional info:
- **Server Revision**: c407534a3e0fceb43939d4d6d4876e936ea3dcc9
- **Again, funnily enough, this behavior is actually appreciable and preferred to how ZAS _should_ be working, as it allows faster gas transfers across multiple zones (or doorways). However given that it's not actually working as expected, and ZAS being the huge beast that it is, this is actually kind of scary and indicates that something in its code is not at all working as it should be.**

**Comment by Leshana** [comment]
This is actually somewhat intentional behavior of ZAS.  A feature was added some time ago ( https://github.com/Baystation12/Baystation12/pull/9718 ) that causes zones to merge even across ZONE_BLOCKED connections if one or both of the areas are small enough ( less than 14 turfs in current code)
If you look at that PR, it explains it was done for exactly the reason you speculate, to speed up gas transfers thru tiny rooms.
