### ISSUE TITLE
Telecomns turrets not working.

### ISSUE THREAD

**Issue by Dhaeleena** [PolarisSS13/Polaris#2491]
#### Brief description of the issue

Four out of six turrets in telecoms doesn't seem to work. The four surrounded by space, the ones always set to lethal are unpowered while the ones in the front set to stun work fine.
#### What you expected to happen

Getting shot to death.
#### What actually happened

I walked past them without an issue.
#### Steps to reproduce

Go to telecoms, go past the first set of turrets, watch as the second and third set of turrets does nothing at all.
#### Additional info:
- **Server Revision**: release - 2016-09-12
  cb178592e5fa174afac6fea075dab2c5727d3483
- **Anything else you may wish to add**: @SpadesNeil says it's because the area for the turrets is wrong."

**Comment by SpadesNeil** [comment]
Yes, the controls for the turrets is in the foyer. The turrets are not in the same power grid area.

Therefore, unless the turrets are controlled by id_tag vars (and they're apparently not), they won't work, at all.

I also vaguely recall someone claiming the turrets don't target/shoot through glass but that's a separate issue. I spaced Dhaeleena just to see if that was the issue but that is not the entirety of the issue here.

**Comment by Nalarac** [comment]
This is no longer an issue as we are on the Southern Cross.
