### ISSUE TITLE
Blindness, Confusion and Blurry Eyes do not modify chance to hit for some attacks

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#2662]
#### Brief description of the issue

Blindness from any source, including genetics, having no eyes, and being flashed does not add the intended 75% to hit malus. #2134
Confusion and blurred vision from flashes also seems to have no effect on chance to hit.
#### What you expected to happen

Someone with no eyes to have difficulty punching you.
#### What actually happened

90%+ accuracy for all melee attacks.
Ranged accuracy seemed to be affected. With an average of 2/5 shots hitting at 1 tile range.
#### Steps to reproduce

Blind self, fire gun/punch friend.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-10-21
  67330d1df626506b796a218c7c261e868060db9c

**Comment by Anewbe** [comment]
Only affects fists.

**Comment by FenodyreeAv** [comment]
Aiming for the head with a knife will not miss, because it gives a 'Stab in the eye' message.
So it also affects snowflake attacks.

**Comment by Atermonera** [comment]
Fixing eyestab shouldn't be hard, because it's only called in two places: `/code/game/objects/items/weapons/tools.dm`, and `code/game/objects/items/weapons/material/kitchen.dm`. Unarmed's hopefully in similarly limited locales, but I'm not about to start a witch hunt in testing every single attack to find any other cases.
