### ISSUE TITLE
Borgs cannot unbuckle other mobs

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#2703]
#### Brief description of the issue
Borgs are able to buckle humans to chairs, but their only method of unbuckling is to totally disassemble the chair.

#### What you expected to happen
If you can buckle them, you can also unbuckle them

#### What actually happened
I had to apply a wrench.

#### Steps to reproduce
Join as borg
Buckle a human to a chair
Try unbuckling them.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MagmaRam** [comment]
Does unbuckling via the "resist" verb no longer work?

**Comment by Atermonera** [comment]
Not trying to unbuckle myself, but rather another being

**Comment by Mechoid** [comment]
Only crisis borgs can unbuckle things at the moment, specifically from rollerbeds, using their own rollerbed module. This could possibly be looked at as an idea for a solution?

**Comment by Nerezza** [comment]
The problem comes from https://github.com/PolarisSS13/Polaris/blob/master/code/_onclick/cyborg.dm where it incorrectly states that robots don't need adjacency checks if they don't have a tool active. I'm going to give it a poke, see how much I break, and possibly come up with a solution or melt something.
