### ISSUE TITLE
Iron and Coal in asteroid walls

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2901]
#### Brief description of the issue
Iron and Coal don't show up in asteroid walls
#### What you expected to happen
It'd be nice to have those ores in the walls, as it was in days of yore.
#### What actually happened
They've been gone a long while, this is just to remind Magma to look into it.
#### Steps to reproduce
1. Start server
2. Try to find iron or carbon
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SilverTalismen** [comment]
They are, As far as I am aware, Dug up with those big massive drills.

**Comment by Anewbe** [comment]
Yeah, but they're supposed to show up like the other ore deposits, in the asteroid walls.

**Comment by Screemonster** [comment]
Having those ores _only_ accessible by the big drills makes mining on foot a damn chore, who wants to make three trips to set up a drill?
And going out in a Ripley is barely better since you _still_ have to faff around setting the drill up. Not good for rock-exploring.

(and put loot crates back in)

**Comment by Anewbe** [comment]
Fixed, crates are back, still don't know about them vaults.
