### ISSUE TITLE
Infections don't work right, can I change them?

### ISSUE THREAD

**Issue by Arokha** [PolarisSS13/Polaris#3009]
Basically when an infection reaches stage 3, it calls die() on the organ (external or internal) in question. First of all, this basically does nothing for external organs in most cases.

If my right arm die()s, I'm actually affected in all of zero ways. I can still use my right hand totally fine, because it doesn't also die() children. This necrotic organ attached to me should really cause sepsis, probably represented by toxin damage, maybe capped based on the number of limbs that are necrotic.

Additionally, die() causes mysterious "damage" damage on the limbs, which is neither brute nor burn, and completely dead, 80 damage, necrotic useless arms don't show up on the advanced medical scanner at all. I'd like to fix that, too.

Is this something you would want? Otherwise I'm just going to code it for VS.

**Comment by SilverTalismen** [comment]
personally as a medical player I would love to see this, as a horribly unrobust player I am terrified by this and want it anyway, But it's not my call

**Comment by Arokha** [comment]
I mean, I'm of the opinion it's not even really a balance issue at the moment, so much as "it does not follow the rules of logic that reality does". If the toxin damage thing should be really low and not kill you, sure whatever. But like... an entirely necrotic limb? No effect? Can still use it? Seems unintentional, code-wise.

**Comment by Woodratt** [comment]
I'd have to talk with Anewbe, but I think we'd may be interested. I'll try and flag him down and see.

**Comment by Anewbe** [comment]
If you make a PR for the changes you've mentioned in the OP, I'd be more than happy to look at it, seems like a good idea.

**Comment by Wickedtemp** [comment]
Can confirm.
- There's no way to detect a 'dead' limb or organ.
- Infections don't cause toxins like they used to.
- The only damage from infections comes from the acute/septic level, when they start directly causing damage to infected internal organs.
- Even that damage is minimal, as peridaxon heals it faster than it can be caused, allowing a person with septic infections in every limb and organ essentially be almost perfectly fine, as long as they have a Peridaxon IV.
- The organ revival surgery doesn't work, or at least, it didn't when I attempted to revive someones dead lungs.
- Dead lungs, speaking of which, can be out-healed with Tricord. Ruptured lungs cause more damage than dead ones. 
There's... a lot of issues with infections, and I'm of the opinion that final-stage infections should just be plain lethal. Dangerous enough so that saving a patient with one without amputating would actually be difficult.
- Almost forgot, septic infections ARE currently lethal in one regard only. If it reaches your heart and kills the organ, that's instant death, no way to prevent it. Dead heart is just immediate death by toxins, which I also think needs to be tweaked. IRL, if your heart stops, you aren't going to just die immediately. You have about 2-4 minutes before brain cells start dying. I think ingame, we can make it so that a dead heart would kill you in about 40-60 seconds, around that time.
