### ISSUE TITLE
Autohiss takes effect in audible emotes.

### ISSUE THREAD

**Issue by nachomeep** [PolarisSS13/Polaris#3104]
#### Brief description of the issue

If you emote with [say "!(EMOTE HERE)"], all Ss are stretched out if you're a Unathi.

#### What you expected to happen

That not to happen, because it's not speech.

#### What actually happened

It happened.

#### Steps to reproduce

Join as a Unathi.
Toggle auto-hiss.
Make an audible emote.

**Comment by Atermonera** [comment]
An audible emote involves sound, so it would be apparent. If it were present on a visual emote there'd be cause for concern.

**Comment by nachomeep** [comment]
No, if say, I do "!sighs." It'll become "sssighs".

**Comment by Atermonera** [comment]
@Neerti , since you were working with saycode extensively recently, can you think of some solution?

**Comment by Atermonera** [comment]
The root cause is that
 `//Autohiss handles auto-rolling tajaran R's and unathi S's/Z's`
  `message = handle_autohiss(message, speaking)`
is in saycode, and handle_autohiss eats the entire message.
Only way I can think of to fix this would be to parse the message for quotations and do something with that

**Comment by Atermonera** [comment]
Ok Neerti has a good idea regarding this, but you'd lose autohiss whenever you use the emote (Which is apparently technically a language in its own right)
