### ISSUE TITLE
Janitor's Trashbag

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3389]
#### Brief description of the issue
Cannot hold more than 5 bullet casings, of any caliber
#### What you expected to happen
To be able to atleast hold 20 of these tiny bullet casings
#### What actually happened
The bag ended up full atfter five or so
#### Steps to reproduce
Shoot a ballistic gun, any caliber
Try to pick up, either by clicking the tile with the bag in hand [which also doesn't work] or having to pick them up by hand
Cry as it takes years to clean up afew
Beat Security officer to death when they fire more.
#### Additional info:master - 2017-04-24
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by PrismaticGynoid** [comment]
A trash bag can hold 8 tiny items, such as bullet casings and cigarette butts, or 4 small items, such as food wrappers or glass shards. Looking at objects/items/weapons/storage/bags.dm suggests the bag should be able to hold at least 21 items, based on what it does for the icons, but max_storage_space is undefined, so it can only hold what I assume is the default, the same amount of storage space as a box. Since the trash bag is a bulky item, and not normal-sized, it should probably hold more than that.

**Comment by SpadesNeil** [comment]
Can we please also make the trash bag able to pick up multiple items again? The reason/excuse for removing/not fixing this was "oh well it makes it too easy to clean up a crime scene." That's a pretty lame excuse if you ask me. Add a cooldown timer if you have to, but don't just remove the functionality entirely.

**Comment by Cameron653** [comment]
This was fixed by https://github.com/PolarisSS13/Polaris/commit/0bfc6de678d5ad6f320516d1d19baae214ddaae4
