### ISSUE TITLE
Circuit Imprinter Can Not Be Deconstructed

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3518]
#### Brief description of the issue
The circuit Imprinters in research can't be deconstructed.
#### What you expected to happen
To be able to deconstruct the circuit imprinters.
#### What actually happened
Your character attempts to feed the crowbar into the machine and it rejects the object.
#### Steps to reproduce
1.) Have a circuit imprinter
2.) Use a screwdriver to open the panel
3.) Try to pry the parts out with a crowbar
#### Additional info:
 - **Server Revision**: master - 2017-06-04  24b35ace2f2fbbc711ece3c5f5b821935e685c25

**Comment by Atermonera** [comment]
I could only reproduce this when the circuit imprinter had glass (Or presumably other stack materials) loaded. Looking at the code, I can't figure out why it's getting through the crowbar check in circuit_imprinter/attackby(), since the only places it could return 0 from that check are when the object isn't a crowbar, or the panel is closed.

**Comment by Nalarac** [comment]
Still an issue on: master - 2017-12-08 11757132352255fa88f0d06597edcb4efa816fa7

**Comment by Leshana** [comment]
Correct, this happens only if sheets of some material are inside. The runtime error occurs when it attempts to eject sheets.
