### ISSUE TITLE
Buckling and Chairs

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3939]
#### Brief description of the issue
Buckling yourself into any chair that can be moved originally let's you run around normally.
#### What you expected to happen
To not be able to move in a chair your buckled into, wheels or not.
#### What actually happened
https://gyazo.com/ee3a140c1964ab413643c7e2a5ef4013
#### Steps to reproduce
Get a office chair, move around
#### Additional info:
 - **Server Revision**: master - 2017-09-24
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Belsima** [comment]
I think I can roll my office chair with my feet irl.

**Comment by SilverTalismen** [comment]
Yeah but in game it requires more then this to move about, plus it has the issue of negating having broken legs and being cuffed in any chair like this will let you just run off I believe.

**Comment by Wickedtemp** [comment]
If you cuff someone to an extremely mobile chair, then that's kinda your fault :p

But yeah, adding on to this, there's another problem with buckling I think. It seems like whenever I'm buckled, and then unbuckle, my hand slots are taken up by an invisible entity and I have to spam "drop" in order to pick anything up after.

**Comment by Wickedtemp** [comment]
Apparently it's just when you unbuckle. Your hand slots become 'frozen' for a little while.

**Comment by Atermonera** [comment]
#4377
