### ISSUE TITLE
Robotic head on organic body turns body into a "robot"

### ISSUE THREAD

**Issue by JuliMc** [PolarisSS13/Polaris#4068]
#### Brief description of the issue

Decapitated bodies, if a robotic prosthetic head is placed on them, turns into a robot that can have a brain put inside of them. They are also fully healed by this. All limbs other then the one changed remain the same.

#### What you expected to happen

For the body to remain lifeless with or without a robotic head.

#### What actually happened

The body was no longer lifeless.

#### Steps to reproduce

1. Decapitate someone organic.
2. Put a robotic head on their shoulders.
3. Put a brain into their body.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** I presume other brains can also be put into the organic-but-not body, other then an MMI.

**Comment by Atermonera** [comment]
Gonna guess that limb reattach is calling robotize on limb_reattach.dm, line 132:
`new_limb.robotize(L.model_info)`
Which for the head, turns into
`/obj/item/organ/external/head/robotize(var/company, var/skip_prosthetics, var/keep_organs)
	return ..(company, skip_prosthetics, 1)`
And then the super, because it's being called from head, robotizes the entire body.
Probably just a 1 or 2 line fix to check that, if the reattached limb is a head, the anchor point is of the same organic-ness as the limb
