### ISSUE TITLE
Shuttles can create ghosts of occupants on the landing pad

### ISSUE THREAD

**Issue by Derpoo** [PolarisSS13/Polaris#4669]
#### Brief description of the issue
If a person (or a ghost) is on the shuttle when it launches a "ghost" sometimes stays behind. These ghosts aren't visible to most people and I don't know why I can see them. These ghosts can't be interacted with, examining turns you in the opposite direction and you cannot throw items at them. Double-clicking them as a ghost teleports you to nullspace. If a person that has a "ghost" uses the shuttle again the "ghosts" disappear.
https://my.mixtape.moe/ksajvq.png
https://my.mixtape.moe/lemgta.png
https://my.mixtape.moe/cuzqdc.png
#### What you expected to happen
I didn't expect to have a shuttle-related spiritual experience.
#### What actually happened
I had a shuttle-related spiritual experience.
#### Steps to reproduce
Unfortunately I don't know, as nobody else could see these ghosts.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
4b6e64111e6521b3d8e9feb3bbac855aac4cc56f 
Only happened on the Sif landing pad One

**Comment by Derpoo** [comment]
Happened to me again, but this time with elevators.

**Comment by MarinaGryphon** [comment]
Seems like it's a problem with Z-level transfer if it occurs with both elevators and shuttles- I think examining an openspace-shadow will cause you to examine the atom it's shadowing (or at least on Aurora it did). Assuming it works similarly to Aurora, you may have turned in the opposite direction because you were facing the mob itself, which had been moved by the shuttle.
I'm not sure how to go about fixing this, but presumably they should be moved upon the mob itself moving- It's possible that they're setting the loc instead of forcemoving them, though, so that may be the issue. I'd have to check to code to see for sure.
