### ISSUE TITLE
Fire axe cabinets are very broken.

### ISSUE THREAD

**Issue by lolman360** [PolarisSS13/Polaris#5388]
#### Brief description of the issue
Fire axe cabinets seem to delete the axe whenever they're unlocked/smashed open.
#### What you expected to happen
To be able to get a robust weapon.
#### What actually happened
A cabinet mysteriously emptying itself.
#### Steps to reproduce
>Find fire axe cabinet
>Hit it with multitool/smash it open
>Cry because the axe is gone and your efforts have gone to waste.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-07-03
2a696dbbff55d22e48d24ff50a53fbcd84b1f7a9 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Tested on all 3 fireaxe cabinets, Bridge, Paramedic Bay and Atmospherics.

**Comment by InvisPinkUnicorn** [comment]
To expand on the issue a bit: using a multitool to open the cabinet results in an empty cabinet and no axe spawning. Smashing the cabinet open results in the cabinet, and the axe inside, disappearing from view (though an invisible object called 'fire axe cabinet' still exists on the tile if right-clicked). This means that it is **impossible to acquire a fire axe** on the server at present, and there are no known workarounds.

**Comment by Mewchild** [comment]
Tested in excess downstream: 
The following vars are of this image, from left to right, in order:
All tests: 
![image](https://user-images.githubusercontent.com/13400422/42425538-6bc5a5d2-82e4-11e8-8719-8878d3df5d79.png)

CONTROL, untouched: 
![](https://i.imgur.com/Eh0yero.png)
Unlocked via multitool:
 ![](https://i.imgur.com/CAvEKPE.png)
Damaged via hit:
 ![image](https://user-images.githubusercontent.com/13400422/42425473-c23c0092-82e3-11e8-8113-6bb3e293e18b.png)
Unlocked via admin fuckery, by setting locked = 0
![image](https://user-images.githubusercontent.com/13400422/42425486-d3528702-82e3-11e8-9061-4aaa9fa7be1f.png)

Unlocked via multitool, then opened: 
![image](https://user-images.githubusercontent.com/13400422/42425510-1ae5e6ea-82e4-11e8-8c44-c5606aab6dff.png)
Damaged to first level of update: 
![image](https://user-images.githubusercontent.com/13400422/42425521-44f59066-82e4-11e8-82ed-28fc2b30ac1f.png)
Broken/4th level of update: 
![image](https://user-images.githubusercontent.com/13400422/42425523-4cc9bb50-82e4-11e8-85c7-218d5b934a7a.png)


The fireaxe was unable to be retrieved on any of these states, and viewing the variables show that the axe IS in the contents.

**Comment by Atermonera** [comment]
https://github.com/PolarisSS13/Polaris/blob/master/code/game/objects/structures/crates_lockers/closets/fireaxe.dm#L27

So basically, whenever you attack a fireaxe cabinet, it checks if a var specific to the cabinet, `var/obj/item/weapon/material/twohanded/fireaxe/fireaxe` is actually pointing at a fireaxe.
If it is, then the iconstate will indicate that with the first digit being 1. Otherwise, that first digit's 0, which means it doesn't think it has a fireaxe.

Now, the problem is that the fireaxe cabinet is of parent type `/obj/structure/closet/`, which spawns all the stuff its supposed to start with by inserting everything in `var/list/starts_with` into the object. The fireaxe cabinet itself doesn't override that, so it's using the parent type's function.
So when you make a new cabinet, it DOES spawn a fireaxe, and it IS put into the cabinet, but because a special var isn't correctly set up, it DOES NOT function as though it had a fireaxe inside of it.

Solution would be to remove the `fireaxe` var and change the checks for it with `if(/obj/[...]/fireaxe in src)`, or override the `New()` function to make it forcibly connect the fireaxe to the var after calling the parent type's `New()`. First option is infinitely preferable, because it's removing spaghetticode instead of adding more.
