### ISSUE TITLE
Observer spawn point bug

### ISSUE THREAD

**Issue by ShadowWatchman** [PolarisSS13/Polaris#5749]
#### Brief description of the issue
On observer spawn: spawn into space with error message "Could not locate an observer spawn point. Use the Teleport verb to jump to the station map."
#### What you expected to happen
Normal observor spawn behaviour
#### What actually happened
As above
#### Steps to reproduce
Observor log in
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 master - 2018-12-01 e145b5c0f7b52ab6ad12e2c1c53445aebb825bb1 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
The only instance I can conceive in which you should encounter this is when you attempt to observe before everything has been initialized, or in this case more specifically before everything has been New()'d, because that allows for the case where the landmarks physically do not exist yet.
Neerti reports having seen it outside this condition, so if you encounter it again, please contact a dev immediately and ideally collect more information about the round type, time, etc, than just "It didn't work," because without that info we have no way of reliably recreating this, and thus cannot debug and fix it.

In general, you should not do anything until initializations have completed, and if possible until roundstart, because you risk key things not being correctly set up or even existing at all.
