### ISSUE TITLE
Merc Ops uplink bugged in terms of avail. equipment

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#576]
As seen in this photo http://i.imgur.com/wrC5TQl.png

Basically while each merc has their own stash of tele-crystals now. Once someone buys equipment the uplink breaks for other (some, not all) mercs, not showing them all of the available equipment. Spookerton can elaborate as he was the one that discovered this bug.

**Comment by ParadoxSpace** [comment]
Can confirm this happens with traitor uplinks too.
http://puu.sh/lWxo1/7a814c5982.jpg

**Comment by Datraen** [comment]
Reaaaally weird, and it would happen with traitor uplinks since they're the same uplink type.

**Comment by Datraen** [comment]
I'd like this to be two separate issues. The one that Spookerton was having was that it was A: In a submenu and B: the can_buy proc wasn't run again for everything (since I didn't touch it because I was making a quick fix until my finals are over.)

ParadoxSpace's issue, however, is a menu displaying issue, which needs to be addressed, Not sure how/why that happened.

**Comment by Datraen** [comment]
Basically I have to have it update on open for NanoUI. Fun bit of work ahead for me.
