### ISSUE TITLE
Electrified Grilles do not shock

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#5958]
#### Brief description of the issue

People are able to smash their way through electrified grilles without gloves and take no damage

#### What you expected to happen

To be shocked by the grille

#### What actually happened

Not shocked by the grille

#### Steps to reproduce

Get a fire axe, find a grille that is supposed to be electrified. Smash grille down

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2019-02-12
a23982d9601bd3b9e6614b3d8de818082d92e7cd 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
The issue is weapons that should be conductive aren't. Like steel fireaxes. And stunbatons. I don't have time to sort through everything for what should and should not be conductive

**Comment by Anewbe** [comment]
Make it the default, says I.

**Comment by elgeonmb** [comment]
steel fireaxes have wood handles. stunbatons obviously have an insulated grip what with the head being constantly electrified. like obviously balance is balance but neither of these examples strike me as particularly egregious

**Comment by Anewbe** [comment]
Balance is a bigger concern that what is or isn't "realistically" conductive. Those grilles are supposed to shock the shit out of under-equipped vandals.

**Comment by MisterLayne** [comment]
@elgeonmb but can't electricity travel through wood. or am i missing something?

**Comment by DasIrrlicht** [comment]
Dry wood with this nice red 'we dunked it in colored plastic so you have a better grip' it is not bad at not conducting.
But if we now had, lets say, a steelrod, with wires atop holding a steel-blade directly at the rod, in your hand... That should preferably shock. And normal, in hand knifes would likely also get you shoked, since grips are made of plasteel.
Lightblades probably will not shock you. Really, having some trigger on weapons asking 'does it protect from shock', would probably help.

**Comment by FenodyreeAv** [comment]
I want one thing with regards to shocked grills, make glass shards cut your hands, or electrocute you when you try and smash a grill with them.

Otherwise you've got the tools to break any grill by the time you get through the window.

**Comment by Anewbe** [comment]
Should have been closed with #5987
