### ISSUE TITLE
Unathi faith not in Religion list

### ISSUE THREAD

**Issue by Mewchild** [PolarisSS13/Polaris#6062]
#### Brief description of the issue
The Unity isn't listed as a religion in the character setup religion list. Given the Tajaran and Skrellian religions were added in https://github.com/PolarisSS13/Polaris/pull/5835, I feel this is simply a small oversight. Can still be used via the "Other" option.

#### What you expected to happen
Be lizard. Have Lizard faith.

#### What actually happened
Be not Lizard. Have not Lizard faith

#### Steps to reproduce
Maybe be Lizard? Maybe not have Lizard faith.

#### Additional info:
Server revision: master - 2019-04-02
effe5434068f435a84ac34b33ae14a5c4cea36a4

**Comment by Cerebulon** [comment]
Put this on the referencing PR but putting it here so it's here:

Not an oversight. This was entirely intentional since following the Unity isn't something people should be able to take willy-nilly without being Unathi whitelisted.

People can enter it custom if their character genuinely has a genuine reason to follow it which would be very rare for a non-Unathi and having it listed in the spawn-list just invites taking it on a whim.

**Comment by Anewbe** [comment]
Could have sworn I commented on this like two days after it was posted, sorry.

As Unathi Loremaster I'm *very* fine with the Unity not being on the religion selector by default. It's something I'd like people to put at least the bare minimum effort into including into their characters, because it's a very active "Live this way" sort of religion, rather than a "Christmas and Easter" religion, if that makes any sense.
