### ISSUE TITLE
Maintenance Drone respawn delay is 10 mins; respawn is 5

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#6376]
#### Brief description of the issue
The maintenance drones still have a ten minute respawn delay while normal respawning is 5.

#### What you expected to happen
To join as drone after 5 minutes

#### What actually happened
No dron, only warnings :(

#### Steps to reproduce
1) join as observer
2) wait for x minutes where 5 < x <= 10
3) try to join as dron
4) no dron :(

#### Additional info:
 - **Server Revision**: f6993f0752e0b47cf8072710119e45c00de02b17

**Comment by DasIrrlicht** [comment]
I did think that was some kind of anti-grief feature, since it is tools+all access needing no list or waiting for a few days, making tider more likely to go for the much inferior assistant-join...

Also, it gives engies a few more minutes time before Ghost-Mc-Gee, just cryoed bartender, comes back from the dead to fix the issues. Or if Mc-Gee comes, he will be faster if he choses a role that actually requires roleplay.
