### ISSUE TITLE
Riding disposals in a locker makes you safe

### ISSUE THREAD

**Issue by Mewchild** [PolarisSS13/Polaris#6392]
#### Brief description of the issue
If you're mailed through disposals, you'll be broken to bits. If you're mailed through inside another container, you're completely safe.

#### What you expected to happen
For individuals stuffed into a locker before being mailed to be battered, broken, and pulped via slamming around the inside of a metal box

#### What actually happened
Our lockers are padded and secure, and act as handy-dandy pneumatic transports.

#### Steps to reproduce
Climb into a locker, close it. Have someone else push you into disposals mailing inlet.

#### Additional info:
 - **Server Revision**: f2d72e6
 - **I believe this is due to how disposals_holder items function, where it's treating "The package of things that entered at the same time" as a single object, thus not checking inside it for mobs

**Comment by DasIrrlicht** [comment]
While this may not be a intentional behavior, I hold it for perfectly reasonable that someone who is no longer getting draged along the side of the tube and has 6 surfaces to press the arms and legs against to reduce their own harm getting less issues.

So while technically a bug, practically I would probably let it stay if it were in my hand. Also, congrats on inventing the NT-Hyperloop.

**Comment by Wickedtemp** [comment]
Pretty sure this has..always been a thing, for years. "Fixing" it would do very little in terms of "actual issues being resolved" and much more in "a fun thing we had is gone".
