### ISSUE TITLE
Traitor Panel "Highlander" button crashes the server

### ISSUE THREAD

**Issue by Kholdstare34** [PolarisSS13/Polaris#6611]
#### Brief description of the issue

Equipping a mob with the Highlander equipment from the traitor panel crashes the server.

#### What you expected to happen

The equipment to be applied properly.

#### What actually happened

The server crashed. 

#### Steps to reproduce

From the staff-side traitor panel, clicking "equip" when making someone a Highlander antagonist template causes the server to crash. 

#### Additional info:
 - **Server Revision**: master - 2020-01-05
daab287c51a3fba8db8b8636af5fc4242f8c2001

**Comment by Schnayy** [comment]
It was never meant to be, kholdstare.
![](https://cdn.discordapp.com/attachments/655216291480862720/664886193233723392/highlander_salty.png)

**Comment by Atermonera** [comment]
Having actually looked into this, can I just say, what the fuck, how did this ever work in the first place.
So, the bug occurs _not_ when you give the player the antag datum, but when you try to _equip_ them.
That code, found here
https://github.com/PolarisSS13/Polaris/blob/9b5573eee63ab9b7afb269d3c826ec29ec9140b4/code/game/antagonist/station/highlander.dm#L30
will, for every obj/item in the player's mob that is NOT an implant, delete it forcefully. This includes limbs, organs, bones, clothes, blood, shoes, effectively the mob is deleted wholesale, but done piecemeal. I _suspect_ that the server crash happens when the upper body is deleted, but since the crash kills the dreamdaemon process itself, like, gone from taskmanager, and the logs I have are unfortunately uninformative, I cannot state this conclusively.
