### ISSUE TITLE
Grave-Drone Ghosttrap does not check for roundstart

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6629]
#### Brief description of the issue
One can join as a Gravedigger-Drone before the round actually starts.
#### What you expected to happen
Not to be a playing pre-roundstart.
#### What actually happened
Gravedrigger asks for your consent.
#### Steps to reproduce
Observe pre-roundstart and wait for RNG.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MisterLayne** [comment]
*Should also note that the grave keeper drone is activated multiple times a round, even when no explorers are near it. I looked into it, but couldn't find the source. Assuming that whatever event drives it checks for mobs, and perhaps the spiders around the area are activating it (or its just on a timer).

**Comment by Atermonera** [comment]
Having actually looked at the code, it's pretty plain why both of these issues are the case.
https://github.com/PolarisSS13/Polaris/blob/7ecdcb40d2cab28b8390d9230bf380decdb0eb4e/code/game/objects/structures/ghost_pods/ghost_pods.dm#L58

If the round fails to start several times in a row, it's possible for the pods' timers to tick down, because they're initialized with all the other objects, and I guess they start processing before the round starts. The timer-based nature also explains why there's no visible cause for them to trigger.
