### ISSUE TITLE
Changeling will not start.

### ISSUE THREAD

**Issue by Zuhayr** [PolarisSS13/Polaris#673]
Looks like the isSynthetic()/NO_SCAN checks may be breaking candidate selection completely.

**Comment by Zuhayr** [comment]
I need input on this and nobody seems willing to give it.

I can either comment out the checks preventing Dionaea and FBPs from being changelings, and allow the mode to start, or I can leave it alone until that code can be fixed. What is desirable?

**Comment by EmperorJon** [comment]
Is there any particular reason as to the code not being fixed other than there's nobody who's got around to doing it? I'm more than happy to take a look at it, otherwise I'd say it needs input from @Neerti. On the one hand it breaks an entire gamemode, but on the other hand robolings don't really make much sense...

**Comment by Zuhayr** [comment]
I can't isolate why it's breaking before roundstart but working after it, or I would have just committed a fix. If you want to sink some time into it feel free.

**Comment by EmperorJon** [comment]
Probably won't be in the next 12 hours but hey, a second pair of eyes can't hurt.

**Comment by EmperorJon** [comment]
Commenting on commit.
