### ISSUE TITLE
[Linux, Lutris] HoP console doesn't work

### ISSUE THREAD

**Issue by listerla** [PolarisSS13/Polaris#6732]
#### Brief description of the issue

When you put an ID into the HoP console with access to use the console, it no longer displays any buttons.

#### What you expected to happen

A good round as HoP, adjusting my ID for all-access as is tradition.

#### What actually happened

I got sad and cryo'd.

#### Steps to reproduce

1. Install any Linux distro of your choice.
2. Install Lutris
3. Install BYOND on Lutris.
4. Attempt to use the HoP console
5. Notice success at first. Then put ID in.
6. All buttons are gone and you must eject ID.

#### Additional info:
 - **Server Revision**: Server revision: master - 2020-02-23 - 2bea80895de462c4dcbe8796b37fdc4d1d800c33 
 - **Anything else you may wish to add** I'm aware Linux isn't intended usage nor a priority, but regardless I know at least 2 or 3 of some of the more active players are based in Linux so increased functionality would be wonderful.

**Comment by Neerti** [comment]
The cause seems to be a `<script>` block that's inside the ID computer's nanoUI template, specifically [this one](https://github.com/PolarisSS13/Polaris/blob/master/nano/templates/identification_computer.tmpl#L62).
Removing it makes the window not be blank, but breaks the job selector menu, so a true fix will presumably need to re-implement that without using a `<script>` block.
