### ISSUE TITLE
Suggestion: A Less Frustrating Cable and Pipe Network

### ISSUE THREAD

**Issue by zylowalsh** [PolarisSS13/Polaris#6757]
I've been floating this idea around for a while but I can't imagine myself ever doing it because it would be a HUGE project for me but I'd like to get the idea out there.

You know how when you place a cable or a pipe and it looks to connect to an existing "network."  Since that network is completely abstract, it got me thinking.  My idea is to add one cable network and two piping networks to the non-natural turfs(Well, if two areas are separated by space, you'd get separate networks).  Just say it is built into the flooring when you build it.  It completely removes the need to map long distance cables and pipes across the map.  Although, someone would have to add some cable-to-turf and pipe-to-turf connection objects as well.  In addition, it prob. be ideal if certain variants of vents and scrubbers could directly connect as well.

Just imagine it.  A bomb goes off in a hallway or a explosive meteor hits maint.  And all you have to repair is the flooring, some walls, vents, scrubbers and maybe even the disposal pipes if you aren't too lazy.  In addition, you don't have to lug around that pipe maker machine that somehow spits out infinite pipe.

In addition, it removes a TON of the clutter on the map and makes it easier and quicker to make map alterations(well, after it is implemented.  If it is ever implemented).

**Comment by Atermonera** [comment]
That would vastly increase the cost of pathing across that network. The way the cable and pipe networks exist right now, they're basically a single loop with a few branching paths. Finding an unbroken path from a power source to a power consumer (one that needs a wire knot, like emitters) is basically a matter of walking along that path (with some form of search algorithm like breadth-first) until you find a power source. If your algorithm works properly, and you run out of path to search, then you don't have any power sources. APCs would become superfluous, because the entire station is a powernet unto itself, so why not just have everything draw directly from the SMES?
This is particularly important with the recent change to make pipes actually leak pressure differentials with outside atmosphere. We added pipe shutoff valves so that if there's a single break in the docks because a single meteor _happened_ to hit there, the whole line of distro doesn't suddenly empty out into space. If all turfs form a network of pipes, then the shutoff valves become completely pointless without physically breaking the map into several space-separated pieces, because a single break anywhere would leak from the whole network.
Overall, I see this as a request to remove mechanics in favor of simplicity and laziness, with ramifications requiring the complete rewriting of atmos pipe and powernet code, which would by and large invalidate atmos tech and electrician as roles (even, arguably, as alt titles).
