### ISSUE TITLE
Outpost SMES Fuckery

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#7213]
#### Brief description of the issue
The two primary SMES units that power the outpost SMES units drain to empty by the 50 minute mark.
The mining outpost (and other outpost SMES units) SMES kept flicking between charging and not charging and the output from 5kW to max output.
#### What you expected to happen
The primary SMES units to sustain power for longer than they do.
The other outpost SMES units to not be finnicky as hell.
#### What actually happened
As above. If the static power thing is merged, I expect the outposts to run out of power rather quickly since it's currently this wonky.
#### Additional info:
 - **Server Revision**: master - 2020-05-19 7d5042cacd16a43ff888802609ba041ca2f2e6a7

**Comment by Atermonera** [comment]
So at present the outpost smes units are actually spawning with an extra regular power coil, because they aren't passing 0 into the super call, so it defaults install_coils to 1. I have no information on what went on during the round the following screenshot was taken in, but based upon time of day it's not unreasonable to presume that nobody fed the pacmans in the mining outpost:
![image](https://puu.sh/FOLnn/6ba82ed06a.png)

**Comment by Nalarac** [comment]
That appears to be one of the individual outpost SMES units (e.g main outpost, mining outpost, xenoarcheology outpost) and not the two primary ones (the two that get hooked up to the PACMANs). The outpost SMES units themselves aren't running out of power because of the static power thing not being in our codebase and you can see that in the load output being stupidly low. You can also see that despite almost no powering being used, its power source (the two main SMES units) are empty as the SMES isn't charging.
