### ISSUE TITLE
New movement code differences to old movement code

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7221]
#### Brief description of the issue
With the old movement code moving 15 tiles took 9 seconds while dragging a body.
With new movement code the same 15 tiles takes 14 seconds.

Aiming movement with old code took 11 seconds.
Aiming movement with new code took 14 seconds.

Magboot old: 8
Magboot new: 9

Hunger old: 6
Hunger new: 7

All of the above old: 16 seconds.
All of the above new 28 seconds.

#### What you expected to happen
Movement while dragging a person or aiming a gun not to have changed significantly.

#### What actually happened
The refactor's slowed down grab movement and aiming movement significantly.

#### Steps to reproduce
Run a server with the old movement, and time crossing the thunderdome.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Ok, further testing with actually printing out next_move and move_delay:
>    | Walk | Run | Grab+Run | Grab+Walk | Aim+Run | Aim+Walk
> New|  5   |  2  |  9       |  12       |  7      |  10
> Old|  5   |  2  |  7       |   7       |  7      |  10

And I suspect that testing grab+aim will similarly disregard the intended delay of aiming and just use the flat value of grab. So for the most part they're the same speed, but anything involving grabs are significantly slower because it's now accounting for other factors
