### ISSUE TITLE
Cannot deconstruct protolathes.

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#765]
After screwdriving the panel open, attempting to crowbar the board out results in a "You can't load Protolathe while it's opened." message.

**Comment by Yoshax** [comment]
Only happens when the prolathe is loaded with materials. Attempting to do so when it's unloaded resulsts in the, "You can't load the Prolathe while it's opened." But still reconstructs.

Applying the crowbar on a Prolathe that's loaded with materials whilst the panel's opened produces a runtime:

runtime error: Cannot create objects of type null.
proc name: dismantle (/obj/machinery/r_n_d/protolathe/dismantle)
  source file: protolathe.dm,85
  usr: Junararhethaa Bayan (/mob/living/carbon/human/tajaran)
  src: Protolathe (/obj/machinery/r_n_d/protolathe)
  usr.loc: the floor (114,160,1) (/turf/simulated/floor/tiled)
  src.loc: the floor (115,160,1) (/turf/simulated/floor/tiled)
  call stack:
Protolathe (/obj/machinery/r_n_d/protolathe): dismantle()
Protolathe (/obj/machinery/r_n_d/protolathe): default deconstruction crowbar(Junararhethaa Bayan (/mob/living/carbon/human/tajaran), the crowbar (/obj/item/weapon/crowbar))
Protolathe (/obj/machinery/r_n_d/protolathe): attackby(the crowbar (/obj/item/weapon/crowbar), Junararhethaa Bayan (/mob/living/carbon/human/tajaran))
the crowbar (/obj/item/weapon/crowbar): resolve attackby(Protolathe (/obj/machinery/r_n_d/protolathe), Junararhethaa Bayan (/mob/living/carbon/human/tajaran))
Junararhethaa Bayan (/mob/living/carbon/human/tajaran): ClickOn(Protolathe (/obj/machinery/r_n_d/protolathe), "icon-x=19;icon-y=8;left=1;scre...")
Junararhethaa Bayan (/mob/living/carbon/human/tajaran): ClickOn(Protolathe (/obj/machinery/r_n_d/protolathe), "icon-x=19;icon-y=8;left=1;scre...")
Protolathe (/obj/machinery/r_n_d/protolathe): Click(the floor (115,160,1) (/turf/simulated/floor/tiled), "mapwindow.map", "icon-x=19;icon-y=8;left=1;scre...")
