### ISSUE TITLE
Cross-Z Buildmode Ladders Not Working

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#7681]
#### Brief description of the issue
In build mode, you can place an "up" and "down" "ladder" which teleports you between the pair when used.
Currently this only works when used on the same z-level or "connected" z-levels (e.g. the station floors), otherwise it just moves you diagonally off the ladder to an adjacent tile.

#### What you expected to happen
Ladder A on say, the surface, to take me to Ladder B on the station.

#### What actually happened
My character is moved in a seemingly random direction off the tile the ladder is on.

#### Steps to reproduce
Enter build mode.
Place ladder on Z-level 1.
Place paired ladder on Z-level 2.
Exit build mode.
Attempt to use ladder.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Tested, could not reproduce, both in correct orientation (Top over bottom) and in reversed orientation. However, the ladders did not work (And performed the described behaviour) if they were not placed directly adjacent vertically (Which is the expected behaviour). Ladders use Move() (I think within a zMove()) to move the mob, and if the dest isn't diagonally adjacent, it outright won't work. In the case of z moves, it does the lateral shift first, and then it attempts the vertical move, which is presumably broken by the fact that it moves you onto floor plating. Not a bug, ladders aren't magic teleporters.

**Comment by Cerebulon** [comment]
I don't know when this was changed, because admin-ladders used to be exactly that; magic teleporters. We used them in events several times in the past to take people to 'off-map' areas, or in the case where this was reported and had been possible in the past, put a ladder in arrivals to 'teleport' people to where the action was happening on the surface because IC the station was off-limits, or in this case, literally killed some guy who arrived late and didnt catch the pain in the arse ooc message to ask to be manually moved.
