### ISSUE TITLE
Autolathes recycle plasteel instead of storing the resource

### ISSUE THREAD

**Issue by Razgriz1032** [PolarisSS13/Polaris#8363]
#### Brief description of the issue
I tried making durasteel with diamond and plasteel.
I put plasteel into the autolathe and I get steel and platinum instead, and I can't mix all three ingredients just to get durasteel because it recycles the plasteel.

#### What you expected to happen
Plasteel in autolathe.

#### What actually happened
Plasteel recycled to steel and platinum.

#### Steps to reproduce
Put plasteel in autolathe.
Put durasteel into autolathe to actually put plasteel in it. Horrible horrible horrible.

PR responsible for this is #7756 I think.

**Comment by Sypsoti** [comment]
May be funky behavior with recycling, but you can't make durasteel in an autolathe here and there are no recipes in the autolathe requiring plasteel. Will keep the issue open regardless because the recycling feature should be looked at.

**Comment by Spookerton** [comment]
I have to agree with the sentiment of the author. This is a bug and oversight; just because there's no specific recipes requiring plasteel doesn't make this a short-sighted behavior. Lathes should either:

- Have a test for material/stack that treats stock resources (rather than items and shards) as stuff to be fed straight into a pool, if one is intended to be available for that resource, Or:

- Go all the way, and always down-convert everything fed in to the lowest level of "made from", then provide a way to up-cycle resources again internally, without printing sheets.

**Comment by Sypsoti** [comment]
I have also been corrected, there is currently a plasteel recipe, apologies.
