### ISSUE TITLE
Blob core chunks do not spawn (/exist?) anymore.

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8903]
#### Brief description of the issue
When killing a blob, it is supposed to drop a core chunk with a specific effect. It doesn't do so anymore.

#### What you expected to happen
For the blob to drop a core chunk related to the type of blob.

#### What actually happened
There is no core chunk.

#### Steps to reproduce
Kill a blob core, then see how there's no core chunk.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add:** (Location if it's a mapping issue, etc) Talked about this briefly with Mechoid; It is assumed that this is the result of #8783.

**Comment by Atermonera** [comment]
Yeah, so I removed them when I transferred most of their effects over to artifact effects - as a mechanical thing they're super inconsistent to access, they have weird uses that don't seem especially well documented, and the code was really weirdly organized - the blob chunk itself basically just had a pointer to the blob overmind datum that spawned it, and that datum told the chunk what to do. The intent of that was to be able to transfer metadata in case someone was crazy enough to turn the chunk back into a core (You can _do_ that???). There was also a general assumption on my end that nobody really used them, because of the inconsistency.

Since apparently people do actually enjoy them, I'm not outright opposed to readding them as-was (We can't _just_ revert because I _am_ attached to the artifact effects that were derived from the chunks). I would really like to see a cleanup of the code, where the _chunk_ knows what it's supposed to do, and just carries the relevant metadata from the parent blob, without that blob informing anything more specific than the type of chunk to create upon its demise.
