### ISSUE TITLE
Stacks of cash cannot be split

### ISSUE THREAD

**Issue by Kholdstare34** [PolarisSS13/Polaris#926]
Stacks of thalers cannot be split by using them anymore. No dialog box appears.

**Comment by Spookerton** [comment]
Not a new bug, or a bug.
This is because stack splitting exists in /obj/item/weapon/spacecash/bundle which is only normally used for odd numbers of thaler. When cashing thaler out of an ATM or splitting bundles, if an existing match for a value is found (eg /obj/item/weapon/spacecash/c1000 ) that object is generated instead, and those do not implement any splitting.
See: https://github.com/PolarisSS13/Polaris/blob/master/code/modules/economy/cash.dm#L71
