### ISSUE TITLE
Neck Grab automatically downs whoever is grabbed.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#948]
Steps to reproduce: Get someone in an aggressive (blue) grab. Upgrade it, and they will fall over.

Additionally, people on the floor can still be used as human shields.

**Comment by Spookerton** [comment]
This is a result of Stun now being roughly synonymous with Weaken, i.e. it causes the mob to set lying 1. This results in the victim falling over when neck grabbed, as neck grabs cause an initial stun(10) on the victim - they then stay prone because mobs cannot stop being prone when aggressive or neck grabbed.

**Comment by Spookerton** [comment]
Stems from the use of [/incapacitated(](https://github.com/PolarisSS13/Polaris/blob/master/code/modules/mob/mob.dm#L159) via [/cannot_stand(](https://github.com/PolarisSS13/Polaris/blob/master/code/modules/mob/mob.dm#L744) which results in stun being treated as a reason to set lying 1 can_move 0.
